### ISSUE TITLE
Publish Karate feature tags on Test Suite and Test objects in ReportPortal

### ISSUE THREAD

**Issue by martinofn3r** [reportportal/agent-java-karate#33]
**Is your feature request related to a problem? Please describe.**
Currently I set tags and attributes on the feature level in a feature file. Those tags/details are supposed to be applied to every test defined in that file. 

The tags/attributes are published to ReportPortal, but only on the Test Suite level, not on Test level. This causes that a couple of widgets (i.. Component Health Check) cannot be used properly, as i.e. I cannot group test results by attributes - ReportPortal requires that those attributes are set on Test level, not Test Suite level.

**Describe the solution you'd like**
All tags/attributes which are assigned on Feature level should be set for Test Suite and Test objects. 

**Describe alternatives you've considered**
Alternatively I can copy/paste all tags/attributes to every single test defined in a feature file. This would be a lot of redundant data and madness to maintain.

**Additional context**
N/A

**Comment by HardNorth** [comment]
@martinofn3r tags and attributes set on the feature level automatically inherited to all deeper levels. They are not displayed at these levels to not overload UI. If in your case they behave differently please post a separate feature into the [core project](https://github.com/reportportal/reportportal), since it's nothing to do with the reporting library or with Karate.
